services:
  pocketbase:
    build: ./pocketbase
    ports:
      - '127.0.0.1:8090:8090'
    volumes:
      - pb_data:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations

volumes:
  pb_data: {}
